version: "3.8"

services:
  local:
    image: registry:2.8
    ports:
      - "5000:5000"
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.gerenciador == 2